### ISSUE TITLE
Hi, I want use Python to call halcon API via c/c++, do you have some advise for me?

### ISSUE THREAD

**Issue by JimXu1989** [dov/hirsch#10]
I try to use ctype, I made a C funciton which return Hobject* as the output, while another function use Hobject* as input, and I make the dll for the functions.
When I use python to call the functions by ctype, I just can not get the right result, I want to get the wisth of the image ,but I always get '1' as output

Thanks a lot!

**Comment by sattlegger** [comment]
Hello @JimXu1989, I just saw your comment because I am watching this repository. I cannot not help you with the current question because, unfortunately, I am not familiar with hirsch. I just wanted to tell you that we at MVTec are currently working at our own python API. I cannot tell you an exact release date yet but it will not be too far in the future. Just check at [mvtec.com](https://www.mvtec.com/products/halcon/newest-features/ ) from time to time. ;) 

@dov I hope that you don't mind me writing this here. Maybe it is also good for you to know that.

**Comment by dov** [comment]
@JimXu1989 Sorry, I can't help you with the ctype binding either. This is not how the hirsch binding works.

@sattlegger (I'd send this privately, but you didn't leave any contact info) Yes, indeed interesting to know about your python binding. If there is anything that I can help with, feel free to send me a direct message. Btw, it would be nice if you a provide me a Halcon license as a thanks for providing the python binding during all these years. Regarding your binding, note that there are lots of ways of creating python bindings, and not all of them are equal. One of the bad examples is/was vtk (at least a few years ago) that used funneled all commands to a single function and then dispatched within C++. That way they lost all the parameter lookup, etc.

**Comment by JimXu1989** [comment]
> Hello @JimXu1989, I just saw your comment because I am watching this repository. I cannot not help you with the current question because, unfortunately, I am not familiar with hirsch. I just wanted to tell you that we at MVTec are currently working at our own python API. I cannot tell you an exact release date yet but it will not be too far in the future. Just check at [mvtec.com](https://www.mvtec.com/products/halcon/newest-features/) from time to time. ;)
> 
> @dov I hope that you don't mind me writing this here. Maybe it is also good for you to know that.

Thanks for the reply, have a nice day!
